apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    {{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | indent 4 }}
    {{- end }}
  annotations:
    checksum/secret: {{ (include (print $.Template.BasePath "/secret.yaml") . ) | sha256sum }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        {{- if .Values.customLabels }}
{{ toYaml .Values.customLabels | indent 8 }}
        {{- end }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.metricsSRVPort }}"
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "3"
          - name: attempts
            value: "2"
          - name: timeout
            value: "1"
          - name: single-request

      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        args:
          {{  if .Values.metricsSRVPort  }}
          - --metrics-srv-port={{ .Values.metricsSRVPort }}
          {{  end  }}
          {{  if .Values.webhookSRVPort  }}
          - --webhook-srv-port={{ .Values.webhookSRVPort }}
          {{  end  }}
          {{  if .Values.incidentWebhookPath  }}
          - --incident-webhook-path={{ .Values.incidentWebhookPath }}
          {{  end  }}
          {{  if .Values.metricsNamespace  }}
          - --metrics-namespace={{ .Values.metricsNamespace }}
          {{  end  }}
          {{  if .Values.analytics.scrapeInterval  }}
          - --analytics-scrape-interval={{ .Values.analytics.scrapeInterval }}
          {{  end  }}
          {{  if .Values.analytics.serviceMetricNames  }}
          - --analytics-service-metric-names={{ .Values.analytics.serviceMetricNames}}
          {{  end  }}
          {{  if .Values.analytics.reportPeriods  }}
          - --analytics-report-periods={{ .Values.analytics.reportPeriods }}
          {{  end  }}
          {{  if .Values.users.scrapeInterval  }}
          - --users-scrape-interval={{ .Values.users.scrapeInterval}}
          {{  end  }}
          {{  if .Values.dtFormat  }}
          - --dt-format={{ .Values.dtFormat}}
          {{  end  }}
          {{  if .Values.debug  }}
          - --debug
          {{  end  }}
        imagePullPolicy: Always
        {{- if .Values.containerResources }}
        {{- if .Values.containerResources.sv }}{{ toYaml .Values.containerResources.sv | trim | nindent 8 }}{{- end }}
        {{- end }}

        ports:
        - name: http
          containerPort: 8080
          protocol: TCP

        env:
          - name: PAGERDUTY_AUTH_TOKEN
            valueFrom: {secretKeyRef: {name: {{ .Chart.Name }}-secret, key: pagerduty_auth_token}}
          - name: INCIDENT_WEBHOOK_SIGNATURE_SECRET
            valueFrom: {secretKeyRef: { name: {{ .Chart.Name }}-secret, key: incident_webhook_signature_secret}}
