apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Chart.Name }}-secret
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  pagerduty_auth_token: {{ .Values.pagerdutyAuthToken | b64enc | quote }}
  incident_webhook_signature_secret: {{ .Values.incidentWebhookSignatureSecret | b64enc | quote }}
