{{ if .Values.webhookSRVPort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
{{- end }}